# Generated by Django 3.2.3 on 2021-06-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0004_reg4'),
    ]

    operations = [
        migrations.CreateModel(
            name='reg5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('E_Mail', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=100)),
                ('Confirm_Password', models.CharField(max_length=100)),
            ],
        ),
    ]
