# Generated by Django 3.2.3 on 2021-06-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0006_reg6'),
    ]

    operations = [
        migrations.CreateModel(
            name='reg7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enter_Price', models.CharField(max_length=100)),
                ('Parent_Category', models.CharField(max_length=100)),
                ('fileToUpload', models.ImageField(upload_to='')),
            ],
        ),
    ]
