# Generated by Django 3.2.3 on 2021-06-08 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0007_reg7'),
    ]

    operations = [
        migrations.CreateModel(
            name='reg8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Password', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=100)),
            ],
        ),
    ]
