# Generated by Django 3.2.3 on 2021-06-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0009_reg9'),
    ]

    operations = [
        migrations.CreateModel(
            name='drop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enter_Price', models.CharField(max_length=100)),
                ('Commission', models.CharField(max_length=100)),
                ('fileToUpload', models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d')),
            ],
        ),
    ]
