# Generated by Django 3.2.3 on 2021-06-10 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0013_auto_20210610_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone_nunmber',
            new_name='phone_number',
        ),
    ]
