# Generated by Django 3.2.3 on 2021-06-10 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0014_rename_phone_nunmber_contact_phone_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='cont',
        ),
    ]
